# Generated by Django 4.2.3 on 2023-12-08 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0002_services_paymentuser_expiredpayments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentuser',
            name='expiration_date',
            field=models.DateField(),
        ),
    ]
